.PHONY: clean All

All:
	@echo "----------Building project:[ 415 - Release ]----------"
	@cd "415" && "$(MAKE)" -f  "415.mk"
clean:
	@echo "----------Cleaning project:[ 415 - Release ]----------"
	@cd "415" && "$(MAKE)" -f  "415.mk" clean
